project:
  type: website

website:
  title: "Gracie Hayes"
  search: false
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: pres.qmd
        text: Research
      - text: CV
        href: Hayes_CV_2025.pdf
  page-footer:
    left: 
      - icon: github
      - text: Gracie Hayes
        href: https://github.com/gshayes/ghayes

format:
  html:
    theme: 
      - stylesheet1.scss
    # mainfont: Montserrat
    toc: false
    link-external-newwindow: true

# format:
#   html:
#     theme:
#       - cosmo
#       - brand
#     css: styles.css
#     toc: true

execute:
  freeze: auto

resources:
  - Hayes_CV_2025.pdf
  
